package Import;

import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;

import java.time.LocalDate;
import java.util.Properties;

public class Email {

    public Email() {
        
    	String to = "jay.solanki@skyzer.co.nz";
        String from = "jaysolanki46@gmail.com";

        final String username = "jaysolanki46@gmail.com";
        final String password = "";

        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "25");

        Session session = Session.getInstance(props,
           new javax.mail.Authenticator() {
              protected PasswordAuthentication getPasswordAuthentication() {
                 return new PasswordAuthentication(username, password);
              }
           });

        try {
           Message message = new MimeMessage(session);

           message.setFrom(new InternetAddress(from));
           message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));
           message.setSubject(getEmailSubject());
          
           BodyPart messageBodyPart = new MimeBodyPart();
           messageBodyPart.setText("Hi Team,\r\n" + 
           		"\r\n" + 
           		"System has done importing process for today for new Vision. \r\n" + 
           		"\r\n" + 
           		"Please find the following link to check Vision & VSM logs, \r\n" + 
           		"http://10.63.192.11/SkyzerProd1/TMSBridge/ImportCheck/index.php\r\n" + 
           		"\r\n" + 
           		"and also find attached log file for process logs.\r\n" + 
           		"\r\n" + 
           		"Thanks.\r\n" + 
           		"\r\n" + 
           		"Kind regards,\r\n" + 
           		"Jay Solanki\r\n" + 
           		"\r\n" + 
           		"[This message was automatically generated by Skyzer TMS import automation tool]\r\n" + 
           		"");
           Multipart multipart = new MimeMultipart();
           multipart.addBodyPart(messageBodyPart);
           messageBodyPart = new MimeBodyPart();
           
           String filename = System.getProperty("user.dir") + "\\logs\\Skyzer-TMS-Logs.log";
           DataSource source = new FileDataSource(filename);
           messageBodyPart.setDataHandler(new DataHandler(source));
           messageBodyPart.setFileName(filename);
           multipart.addBodyPart(messageBodyPart);

           message.setContent(multipart);
           Transport.send(message);
           System.err.println("Sent");
    
        } catch (MessagingException e) {
           throw new RuntimeException(e);
        }
    }	  
	
    public String getEmailSubject() {
		
		String subject = "";
		LocalDate currentMonthLocalDate = LocalDate.now();
		int currentDay = currentMonthLocalDate.getDayOfMonth();
		int currentMonth = currentMonthLocalDate.getMonthValue();
		int currentYear = currentMonthLocalDate.getYear();
		String day = "";
		String month = "";
		String currentDateStr = "";
		
		if(String.valueOf(currentDay).length() < 2) {
			day = "0" + currentDay;
		} else {
			day = String.valueOf(currentDay);
		}
		
		if(String.valueOf(currentMonth).length() < 2) {
			month = "0" + currentMonth;
		} else {
			month = String.valueOf(currentMonth);
		}
		
		currentDateStr = day + "/" + month + "/" + currentYear;
		
		LocalDate lastMonthLocalDate = currentMonthLocalDate.minusMonths(1);
		int lastDay = lastMonthLocalDate.getDayOfMonth();
		int lastMonth = lastMonthLocalDate.getMonthValue();
		int lastYear = lastMonthLocalDate.getYear();
		String lastDateStr = "";
		
		if(String.valueOf(lastDay).length() < 2) {
			day = "0" + lastDay;
		}
		
		if(String.valueOf(lastMonth).length() < 2) {
			month = "0" + lastMonth;
		}
		
		lastDateStr = day + "/" + month + "/" + lastYear;
		
		subject = "Daily Import" + " (" + lastDateStr + " to " + currentDateStr + ") ";
		
		return subject;
	}
}
